# Use an official Node.js runtime as a parent image
FROM node:14

# Set the working directory to /app/client
WORKDIR /app/client

# Copy the package.json and package-lock.json files to the container
COPY package*.json ./

# Install the dependencies
RUN npm install

# Copy the client files to the container
COPY ./ ./

# Expose the port the client will listen on
EXPOSE 3000

# Run the client
CMD ["npm", "run", "start"]
