# Use an official Node.js runtime as a parent image
FROM node:14

# Set the working directory to /app/server
WORKDIR /app/server/api

# Copy the package.json and package-lock.json files to the container
COPY package*.json ./

# Install the dependencies
RUN npm install

# Copy the server files to the container
COPY ./ ./

# Expose the port the server will listen on
EXPOSE 5000

# Run the server
CMD ["npm", "run", "seed"]
