name: Build and Deploy
on:
  push:
    branches: [main]

env:
  AZURE_WEBAPP_NAME: <your-webapp-name>
  IMAGE_NAME: <your-image-name>
  IMAGE_TAG: ${{ github.sha }}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - run: npm ci
      - run: npm test

  build-and-deploy:
    name: Build and Deploy
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # - name: Build and push Docker image to Azure Container Registry
      #   uses: azure/docker-login@v1
      #   with:
      #     login-server: <your-registry-name>.azurecr.io
      #     username: ${{ secrets.REGISTRY_USERNAME }}
      #     password: ${{ secrets.REGISTRY_PASSWORD }}
      # - run: |
      #     docker build . --file Dockerfile.prod --tag $IMAGE_NAME:$IMAGE_TAG
      #     docker tag $IMAGE_NAME:$IMAGE_TAG $AZURE_WEBAPP_NAME.azurecr.io/$IMAGE_NAME:$IMAGE_TAG
      #     docker push $AZURE_WEBAPP_NAME.azurecr.io/$IMAGE_NAME:$IMAGE_TAG
      # - name: Deploy to Azure Web App for Containers
      #   uses: azure/webapps-container-deploy@v1
      #   with:
      #     app-name: ${{ env.AZURE_WEBAPP_NAME }}
      #     images: ${{ env.AZURE_WEBAPP_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
      #     registry-login-server: <your-registry-name>.azurecr.io
      #     registry-username: ${{ secrets.REGISTRY_USERNAME }}
      #     registry-password: ${{ secrets.REGISTRY_PASSWORD }}
