name: Build and Deploy

on:
  push:
    branches:
      - main

env:
  AZURE_WEBAPP_NAME: MyRecipePal

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - run: npm ci
      - run: npm test -- --detectOpenHandles

  e2e:
    name: E2E
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: npm start
          wait-on: "http://localhost:3000"

  build_and_deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    env:
      RECIPES_JSON_FILE: /Users/Abdalla.Yusuf/Documents/recipes.json
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - run: npm ci
      - run: npm run build
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }} ${{secrets.AZURE_RESOURCE_GROUP}} ${{secrets.AZURE_WEBAPP_NAME}}
      - name: Azure Web App deploy
        run: az webapp deployment source config-zip --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --name ${{ secrets.AZURE_WEBAPP_NAME }} --src ./build.zip
