name: Build and Deploy

on:
  push:
    branches:
      - main

env:
  AZURE_WEBAPP_NAME: MyRecipePal
  IMAGE_NAME: <your-image-name>
  IMAGE_TAG: ${{ github.sha }}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - run: npm ci
      - run: npm test -- --detectOpenHandles

  build_and_deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - run: npm ci
      - run: npm run build
      - name: Docker build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
      - name: Azure Web App deploy
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          images: "${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}"
