name: Build and Deploy
on:
  push:
    branches: [main]

env:
  AZURE_WEBAPP_NAME: <your-webapp-name>
  IMAGE_NAME: <your-image-name>
  IMAGE_TAG: ${{ github.sha }}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - run: npm ci
      - run: npm test -- --detectOpenHandles
